[package]
name = "hreq-h1"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2018"

[dependencies]
futures-channel = { version = "0.3", default-features = false, features = ["sink", "std"] }
futures-io = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "io"] }
http = "0.2"
httparse = "1"
log = "0.4"

[dev-dependencies]
env_logger = "0.7"
pretty_env_logger = "0.4"
tokio = { version = "0.2", default-featulres = false, features = ["rt-threaded", "net", "tcp", "time", "fs", "macros"] }